// packages/wds-client/src/components/Footer.tsx
import React from 'react'
import styled, { css } from '../styles/styled-components'

import Mailto from './Mailto'

const StyledFooter = styled.footer`
  display: flex;
  align-items: center;
  justify-content: center;
  ${({ color }: any) =>
    css`
      background: ${color};
    `};
  min-height: 20vh;
  width: 100%;
`

const Footer = ({ color = 'primaryBlue' }) => (
  <StyledFooter color={color}>
    <Mailto email="richard.vancamp@gmail.com" />
  </StyledFooter>
)

export default Footer

// packages/wds-site-v4/src/components/Footer.svelte
<script>
	import Mailto from './Mailto.svelte'
</script>

<style>
	.footer {
		min-height: 10rem;
		border-bottom: 1px solid var(--brand-primary);
	}
</style>

<div class="footer flex text-center justify-center align-middle">
	<div class="flex flex-col justify-center mb-8">
		<Mailto email="richard.vancamp@gmail.com">Contact us</Mailto>
	</div>
</div>
